; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "WinVE"
#define MyAppVersion "1.1.3"
#define MyAppPublisher "opkelde"
#define MyAppURL "https://github.com/opkelde/WinVE"
#define MyAppExeName "WinVE.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{27F7CD5A-57D7-4619-B622-C4D05496FD82}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=.\LICENSE
InfoBeforeFile=.\pre-install-info.txt
InfoAfterFile=.\post-install-info.txt
PrivilegesRequired=lowest
OutputDir=.\inno
OutputBaseFilename=WinVE-Debug
SetupIconFile=.\img\icon.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "autostart"; Description: "Start WinVE automatically when Windows starts"; GroupDescription: "Startup Options"

[Dirs]
Name: "{app}"; Permissions: users-modify
Name: "{userappdata}\WinVE"; Permissions: users-modify

[Files]
Source: ".\dist\WinVE\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\dist\WinVE\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: ".\.env.example"; DestDir: "{userappdata}\WinVE"; DestName: ".env.example"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Registry]
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "WinVE"; ValueData: "{app}\{#MyAppExeName}"; Tasks: autostart; Flags: uninsdeletevalue

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "https://github.com/opkelde/WinVE"; Description: "🐙 Visit GitHub Repository"; Flags: shellexec skipifsilent postinstall unchecked

[Code]
var
  ESPHomeDevicePage: TInputQueryWizardPage;
  ESPHomeHACredsPage: TInputQueryWizardPage;

procedure InitializeWizard;
begin
  // Step 1: ESPHome — device settings
  ESPHomeDevicePage := CreateInputQueryPage(wpSelectTasks,
    'WinVE Satellite Configuration', 'Device identity in Home Assistant',
    'Configure how WinVE appears in Home Assistant:' + #13#10 + #13#10 +
    'After installation, add the device in Home Assistant:' + #13#10 +
    '  Settings → Devices & Services → Add Integration → ESPHome' + #13#10 +
    '  Enter this PC''s IP address and the port below.' + #13#10 + #13#10 +
    'WinVE will be auto-discovered via mDNS if your network supports it.');
  ESPHomeDevicePage.Add('Device Name (shown in HA):', False);
  ESPHomeDevicePage.Add('Port (default: 6053):', False);
  ESPHomeDevicePage.Values[0] := 'WinVE';
  ESPHomeDevicePage.Values[1] := '6053';

  // Step 2: ESPHome — optional HA credentials (for media player volume control)
  ESPHomeHACredsPage := CreateInputQueryPage(ESPHomeDevicePage.ID,
    'Optional: Media Player Volume Control', 'Home Assistant credentials (optional)',
    'WinVE can automatically lower the volume of your media players (speakers, TVs)' + #13#10 +
    'while you speak and restore it after the response.' + #13#10 + #13#10 +
    'This feature requires a connection to Home Assistant.' + #13#10 +
    'Leave both fields empty to skip — you can configure this later in Settings.' + #13#10 + #13#10 +
    'HOW TO GET AN ACCESS TOKEN:' + #13#10 +
    '1. Open Home Assistant → Profile (your name, bottom left) → Security' + #13#10 +
    '2. Scroll to "Long-Lived Access Tokens"' + #13#10 +
    '3. Click "CREATE TOKEN", name it "WinVE Desktop"' + #13#10 +
    '4. Copy the token and paste below');
  ESPHomeHACredsPage.Add('HA Server Address (e.g. 192.168.1.100:8123):', False);
  ESPHomeHACredsPage.Add('Long-Lived Access Token (optional):', True);
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  EnvContent: string;
  EnvPath: string;
  EnvDir: string;
  DeviceName: string;
  ESPHomePort: string;
  HAHost: string;
  HAToken: string;
begin
  if CurStep = ssPostInstall then begin
    EnvDir := ExpandConstant('{app}');
    EnvPath := EnvDir + '\.env';

    if not DirExists(EnvDir) then
      CreateDir(EnvDir);

    HAHost := ESPHomeHACredsPage.Values[0];
    HAToken := ESPHomeHACredsPage.Values[1];

    DeviceName := ESPHomeDevicePage.Values[0];
    if DeviceName = '' then DeviceName := 'WinVE';
    ESPHomePort := ESPHomeDevicePage.Values[1];
    if ESPHomePort = '' then ESPHomePort := '6053';

    // Build .env
    EnvContent :=
      '# === CONNECTION ===' + #13#10 +
      'CONNECTION_MODE=esphome' + #13#10 +
      'HA_HOST=' + HAHost + #13#10 +
      'HA_TOKEN=' + HAToken + #13#10 +
      'HA_PIPELINE_ID=' + #13#10 +
      '' + #13#10 +
      '# === ESPHOME SATELLITE MODE ===' + #13#10 +
      'DEVICE_NAME=' + DeviceName + #13#10 +
      'ESPHOME_PORT=' + ESPHomePort + #13#10 +
      '' + #13#10 +
      '# === ACTIVATION ===' + #13#10 +
      'HA_HOTKEY=ctrl+shift+h' + #13#10 +
      '' + #13#10 +
      '# === AUDIO ===' + #13#10 +
      'HA_SAMPLE_RATE=16000' + #13#10 +
      'HA_CHANNELS=1' + #13#10 +
      'HA_FRAME_DURATION_MS=30' + #13#10 +
      'HA_PADDING_MS=300' + #13#10 +
      'HA_MICROPHONE_INDEX=-1' + #13#10 +
      'HA_OUTPUT_DEVICE_INDEX=-1' + #13#10 +
      'HA_OUTPUT_SAMPLE_RATE=-1' + #13#10 +
      '' + #13#10 +
      '# === VOICE DETECTION (VAD) ===' + #13#10 +
      'HA_VAD_MODE=3' + #13#10 +
      'HA_SILENCE_THRESHOLD_SEC=1.5' + #13#10 +
      '' + #13#10 +
      '# === INTERFACE & PERFORMANCE ===' + #13#10 +
      'HA_ANIMATIONS_ENABLED=true' + #13#10 +
      'HA_RESPONSE_TEXT_ENABLED=true' + #13#10 +
      'HA_SHOW_LISTENING_INDICATOR=true' + #13#10 +
      '' + #13#10 +
      '# === NETWORK ===' + #13#10 +
      'ANIMATION_PORT=8765' + #13#10 +
      '' + #13#10 +
      '# === AUDIO FEEDBACK ===' + #13#10 +
      'HA_SOUND_FEEDBACK=false' + #13#10 +
      'HA_CONTINUE_ON_QUESTION=false' + #13#10 +
      '' + #13#10 +
      '# === WAKE WORD DETECTION ===' + #13#10 +
      'HA_WAKE_WORD_ENABLED=true' + #13#10 +
      'HA_WAKE_WORD_MODELS=computer_v2' + #13#10 +
      'HA_WAKE_WORD_THRESHOLD=0.5' + #13#10 +
      'HA_WAKE_WORD_VAD_THRESHOLD=0.3' + #13#10 +
      'HA_WAKE_WORD_NOISE_SUPPRESSION=false' + #13#10 +
      '' + #13#10 +
      '# === MEDIA PLAYER VOLUME MANAGEMENT ===' + #13#10 +
      'HA_MEDIA_PLAYER_ENTITIES=' + #13#10 +
      'HA_MEDIA_PLAYER_TARGET_VOLUME=0.3' + #13#10 +
      '' + #13#10 +
      '# === DEBUG ===' + #13#10 +
      'DEBUG=true';

    SaveStringToFile(EnvPath, EnvContent, False);
  end;
end;